import Head from "next/head"
import { Inter } from "next/font/google"
import { useQuery } from "@tanstack/react-query"
import { Fragment } from "react"

const inter = Inter({
  weight: "400",
  subsets: ["latin"],
})

export default function Home() {
  const fetchPokemon = async (pokemonNumber: any) => {
    const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${pokemonNumber}`).then((res) =>
      res.json()
    )
    return res // Return the Pokémon data
  }

  const fetchPokemonArray = async () => {
    const pokemonArray = []
    for (let i = 1; i <= 30; i++) {
      try {
        const pokemonData = await fetchPokemon(i)
        pokemonArray.push(pokemonData)
      } catch (error) {
        console.error(error)
      }
    }
    return pokemonArray
  }

  const {
    isLoading,
    error,
    data: pokemon,
  } = useQuery([`fetch-top-20-pokemon`], () => fetchPokemonArray())

  console.log({ pokemon })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <h1 style={{ textAlign: "center", margin: "4rem" }}>Pokedex</h1>
        {isLoading && <h2>Loading...</h2>}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr 1fr",
            alignItems: "center",
            justifyContent: "center",
            justifySelf: "center",
          }}
        >
          {pokemon?.map((itm, index) => (
            <div
              style={{ display: "flex", alignItems: "center", flexDirection: "column" }}
              key={index}
            >
              <img alt={itm?.name} src={itm?.sprites?.front_default} />
              <div>{itm?.name}</div>
            </div>
          ))}
        </div>
      </main>
    </>
  )
}
